"""empty message

Revision ID: b774153faa52
Revises: c4ea5488cf4d
Create Date: 2024-10-05 01:11:20.786855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b774153faa52'
down_revision = 'c4ea5488cf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'ciudad', ['ciudad_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ciudad_id')

    # ### end Alembic commands ###
