"""empty message

Revision ID: c4ea5488cf4d
Revises: 7ac1a9f92040
Create Date: 2024-10-05 01:08:22.677454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ea5488cf4d'
down_revision = '7ac1a9f92040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('himno', sa.String(length=250), nullable=False),
    sa.Column('color_bandera', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciudad')
    # ### end Alembic commands ###
